research_task:
  description: >
    Conduct a thorough research about {user_input}
    Make sure you find any interesting and relevant information from external online sources that match 
    the learner's specific needs, learning level, and preferences.
  expected_output: >
    A list of relevant educational resources with detailed information about each, including
    source links, content type, difficulty level, and relevance to the learner's needs.
  agent: educational_researcher
  output_key: research_results